from typing import Protocol

from slideforge.application.ai.config import AIConfig
from slideforge.application.ai.contracts import (
    ContentSummarizer,
    DocumentAnalyzer,
    ImageSuggestionProvider,
    PresentationPlannerAI,
    PresentationReviewer,
    SlideLayoutAdvisor,
    SpeakerNotesGenerator,
    ThemeAdvisor,
)
from slideforge.application.ai.models import AIProviderInfo


class AIProvider(Protocol):
    @property
    def info(self) -> AIProviderInfo: ...

    @property
    def config(self) -> AIConfig: ...

    def document_analyzer(self) -> DocumentAnalyzer: ...
    def presentation_planner(self) -> PresentationPlannerAI: ...
    def slide_layout_advisor(self) -> SlideLayoutAdvisor: ...
    def content_summarizer(self) -> ContentSummarizer: ...
    def theme_advisor(self) -> ThemeAdvisor: ...
    def image_suggestion_provider(self) -> ImageSuggestionProvider: ...
    def speaker_notes_generator(self) -> SpeakerNotesGenerator: ...
    def presentation_reviewer(self) -> PresentationReviewer: ...
